services:
  - type: web
    name: astro-cloudflare-personal-website
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      # - key: SENTRY_AUTH_TOKEN
      #   sync: false
      # - key: GITHUB_TOKEN
      #   sync: false
      # - key: CODECOV_TOKEN
      #   sync: false
